<?php

namespace MongoUI\Core;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../core/Registry.php';

/**
 * Test class for Registry.
 * Generated by PHPUnit on 2010-09-22 at 19:28:13.
 */
class RegistryTest extends \PHPUnit_Framework_TestCase {

    /**
     * Nothing to do here yet.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testSet().
     */
    public function testSet() {
        // Set some value.
        Registry::set("test", "testValue");
        
        try {
            // Set value again.
            Registry::set("test", "anotherTestValue");
        } catch (\Exception $expected) {
            return;
        }
        $this->fail('An expected exception has not been raised.');
    }

    /**
     * 
     */
    public function testGet() {
        // Set test key/value
        Registry::set('getTest', 'getValue');
        // Test if it's possible to retrieve it
        $this->assertEquals('getValue', Registry::get('getTest'));

        // Should return null if key doesn't exist.
        $this->assertNull(Registry::get('not_existing_key'));
    }

    /**
     * @todo Implement testHas().
     */
    public function testHas() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
