<?php

namespace MongoUI\Core;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../core/Translate.php';

/**
 * Test class for Translate.
 * Generated by PHPUnit on 2010-09-22 at 01:52:59.
 */
class TranslateTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Translate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = Translate::getInstance();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testGetInstance().
     */
    public function testGetInstance() {
        $instance = Translate::getInstance();
        // Check if getInstance() returns correct object.
        $this->assertTrue(is_a($instance, 'MongoUI\Core\Translate'));
    }

    /**
     * @todo Implement testLoadLanguage().
     */
    public function testLoadLanguage() {
    }

    /**
     * @todo Implement testGetTranslation().
     */
    public function testGetTranslation() {
    }

    /**
     * @todo Implement testGetLanguageToLoad().
     */
    public function testGetLanguageToLoad() {
    }

    /**
     * @todo Implement testGetAvailableLanguages().
     */
    public function testGetAvailableLanguages() {
    }

    /**
     * @todo Implement testIsValidLanguage().
     */
    public function testIsValidLanguage() {
        // Testing for german (de_DE) translation
        $this->assertTrue($this->object->isValidLanguage('de_DE'));
        // Checking result for invalid language
        $this->assertFalse($this->object->isValidLanguage('xx_XX'));
    }

}

?>
